extends:
  - airbnb
  - plugin:jest/recommended
rules:
  react/prefer-stateless-function: 0
  react/jsx-filename-extension:
    - 1
    - extensions:
      - .js
      - .jsx
  import/prefer-default-export: 0
  arrow-body-style: 0
settings:
  import/resolver:
    node:
      paths:
        - src/
