language: node_js
node_js: node
cache: yarn
stages:
  - name: test
    if: type = pull_request
  - name: deploy
    if: type = push AND branch = develop
jobs:
  include:
    - stage: test
      script: yarn test
    - stage: test
      script: ./node_modules/.bin/eslint src/
    - stage: deploy
      script: echo "Deploying to GitHub Pages..."
      before_deploy: npm run build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: build
        target-branch: master
        on:
          branch: develop
