language: node_js
node_js: node
sudo: false
cache:
  directories:
    - node_modules
install: npm ci
stages:
  - name: lint
    if: type = pull_request
  - name: test
    if: type = pull_request
  - name: build
    if: type = push
  - name: deploy
    if: type = push
jobs:
  include:
    - stage: test
      script: npm test
    - stage: lint
      script: ./node_modules/.bin/eslint src/
    - stage: build
      script: npm run build
    - stage: deploy
      script: skip
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: build
        on:
          branch: master
