language: node_js
node_js:
  - "node"
  - "7"
cache:
  directories:
    - "node_modules"
stages:
  - name: test
    if: pull_request
  - name: build
    if: branch = develop
  - name: deploy
    if: branch = develop
jobs:
  include:
    - stage: test
      script: npm test
    - stage: build
      script: npm build
    - stage: deploy
      script: skip
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        keep-history: true
        local-dir: build
        target-branch: master
        on:
          branch: develop
