language: node_js
node_js: node
sudo: false
cache:
  directories:
    - node_modules
install: npm ci
stages:
  - name: lint
    if: type = pull_request
  - name: test
    if: type = pull_request
  - name: build
    if: type = push AND branch = develop
  - name: deploy
    if: type = push AND branch = develop
jobs:
  include:
    - stage: test
      script: npm test
    - stage: lint
      script: ./node_modules/.bin/eslint src/
    - stage: build
      script: npm run build
    - stage: deploy
      script: echo "Deploying to GitHub Pages..."
      before_deploy: npm run build
      deploy:
        provider: pages
        skip-cleanup: true
        github-token: $GITHUB_TOKEN
        local-dir: build
        target-branch: master
        on:
          branch: develop
