language: node_js
node_js:
  - "iojs"
  - "7"
cache:
  directories:
    - "node_modules"
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  on:
    branch: master
